### ISSUE TITLE
Spaces in TokenName and Ticker?

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-metadata-submitter#18]
Hi,

@KtorZ 

in reference to https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Primitive/Types/TokenPolicy.hs

are Spaces in the TokenName and the TokenTicker allowed?

TokenName i think yes, but in the Ticker i am not 100% sure?

Thx.

**Comment by KtorZ** [comment]
Yes they are :+1:
