### ISSUE TITLE
DecoderErrorDeserialiseFailure

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-metadata-submitter#5]
I tried a few things with the cardano-metadata-submitter, but running:

`./cardano-metadata-submitter 34250edd1e9836f5378702fbf9416b709bc140e04f668cc3552085184154414441636f696e --name "ATADAcoin" --description "just a short description..." --policy "7b20226b657948617368223a20223435643730653534663362356539633561326230636434313730323831393762643666356661353337386332663565626138393636373864222c202274797065223a202273696722207d0a"`

results in:
`option --policy: Error in $: DecoderErrorDeserialiseFailure "Script" (DeserialiseFailure 0 "expected list len")`

the script is:
```
cat assets/machtl.policy.script
{ "keyHash": "45d70e54f3b5e9c5a2b0cd417028197bd6f5fa5378c2f5eba896678d", "type": "sig" }
```

converted into base16/hex via:
`$(cat assets/machtl.policy.script | xxd -ps -c 256 | tr -d '\n')`

what am i doing wrong? :smiley:

**Comment by gitmachtl** [comment]
So i saw that you used this script policy example:
```

{
    "type": "all",
    "scripts": [
        {
            "keyHash": "2B0C33E73D2A70733EDC971D19E2CAFBADA1692DB2D35E7DC9453DF2",
            "type": "sig"
        }
    ]
}
```

But actually also this short one is legit:
{
            "keyHash": "2B0C33E73D2A70733EDC971D19E2CAFBADA1692DB2D35E7DC9453DF2",
            "type": "sig"
}

At least thats what all the examples show right now. If now, please let me know and we update the tools, thx!

**Comment by gitmachtl** [comment]
ok, the latest version that also accepts the policy directly as a json file works :smiley:

**Comment by KtorZ** [comment]
@gitmachtl yes indeed, there was a bit of more work to do on the tool. I normalized a bit the API to be interoperable with the cardano-cli's formats. May I close this ticket?

**Comment by gitmachtl** [comment]
yes thx. just trying to figure out how to do a bech32 (blake2b) policyID|assetName converting on the cli ...

**Comment by KtorZ** [comment]
https://github.com/input-output-hk/bech32/releases/tag/v1.1.0

**Comment by gitmachtl** [comment]
got it, was a bit more complicated via just bash. raw decode -> blake2 encode -> bech32 :-)
