### ISSUE TITLE
Ticker name with 5 chars

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-metadata-submitter#6]
Why is there a limitation to only 4 chars? So, non of the Pools can also generate NativeAssets with there own Name!? Please increase this to at least 5 chars.

**Comment by sp33dy** [comment]
I thought exactly the same thing. We have pools with, Doh, 5 letters... Quite a weird limit.

**Comment by gitmachtl** [comment]
Integrated... can be closed
